{% set name = "buscar" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.10
    - pip
    - poetry-core >=1.8.0
  run:
    - python >=3.10,<3.14
    - beartype >=0.21.0,<0.22.0
    - numpy >=2.2.5,<3.0.0
    - polars >=1.29.0,<2.0.0
    - pot >=0.9.5,<0.10.0
    - scikit-learn >=1.6.1,<2.0.0
    - scipy >=1.15.3,<2.0.0
    - statsmodels >=0.14.4,<0.15.0
    - umap-learn >=0.5.9.post2,<0.6.0

test:
  imports:
    - buscar
  commands:
    - python -c "import buscar; print(buscar.__name__)"

about:
  home: https://github.com/WayScience/buscar
  summary: A framework for prioritizing compounds in high-content imaging screens using single-cell profiles.
  license: MIT

extra:
  recipe-maintainers:
    - erikserrano
